### ISSUE TITLE
복잡한 반환 타입 체계

### ISSUE THREAD

**Issue by Sung-Gi-Hyeon** [Sung-Gi-Hyeon/Calc#5]
지금의 소스에서는 파서가 던진 노드를, Evaluator.Evaluate()가 연산자(OperatorNode)를 반환할지, 값(ValueNode)를 반환할지, 모르는 상태이기 때문에, object로 반환한다.</br>
이렇게 받은 object를 사용할 때는, 잘 사용할 수 있으나, 테스트를 작성하기 위해서 사용하기에는 난감한 상황이 발생한다.
이런 복잡한 타입 체계를 과연, 오버로드로 여러 타입의 값을 돌려주는게 옳은 방법일까?

**Comment by phillyai** [comment]
Node 들의 공통 부모인 Node를 리턴하게 하고 타입 패턴매칭을 하면 어때

**Comment by Sung-Gi-Hyeon** [comment]
Node로 반환하면, 사용하는 측에서 패턴매칭해서 Evaluator.Evaluate()의 값을 상황따라 쓰다는 건가요?</br>
<pre>dynamic rLeft = left.Evaluate();</br>dynamic rRight = right.Evaluate();</pre>
이부분도  받은 결과 노드의 패턴을 보고 상황따라 다른 연산을하도록 바꿔야 할까요?</br>

**Comment by phillyai** [comment]
헉 내가 어젯밤에 졸려서 헛소리를..결과값 계산할때는 dynamic 쓰는게 나아

**Comment by Sung-Gi-Hyeon** [comment]
그럼. 그냥 마지막에 계산된 값을 object에서 integer, decimal, string으로 바꿔주는 메소드를 만들어서 강타입 같이(?) 사용하는게 좋을까요?

**Comment by phillyai** [comment]
언어가 컴파일 타임에서 타입 검사가 이루어지면 걱정없이 dynamic을 써도 되고 그렇지 않으면 터질 걱정이 있다면 그냥 try catch로 잡거나 타입 일일히 비교해서 실행 전에 검사를 하겠지..?

**Comment by Sung-Gi-Hyeon** [comment]
<pre>public dynamic Evaluate()</pre>
이렇게 반환을 dynamic으로 object에서 바꿨는데, 이렇게 바꾸니, 테스트를 작성할때, 에러가 생깁니다.

<pre>
Lexer lexer = new Lexer("123+0.001*10");
Parser parser = new Parser(lexer.Lex());
Evaluator evaluator = new Evaluator(parser.Parse());
decimal expect = 123.010m;

Assert.AreEqual(expect, evaluator.Evaluate());
</pre>
이렇게 빌드하려하면, "'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create' 멤버가 필요한 컴파일러가 없습니다."로 인해 테스트가 빌드되지 않는데, 테스트를 어떻게 작성할 수 있을까요?

**Comment by phillyai** [comment]
그거 Nuget에서 라이브러리 두개 설치해야함
```
Microsoft.CSharp
System.Dynamic.Runtime
```
이 두개

**Comment by Sung-Gi-Hyeon** [comment]
일단은 해결
